"""Direct email delivery using Python stdlib smtplib — no extra packages needed."""

from __future__ import annotations

import logging
import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

logger = logging.getLogger(__name__)


def send_report_email(
    to_email: str,
    topic: str,
    report: str,
    task_id: str,
    word_count: int = 0,
    avg_confidence: float = 0.0,
    cost_usd: float = 0.0,
) -> bool:
    """Send research report via Gmail SMTP. Returns True on success."""
    gmail_user = os.getenv("GMAIL_USER", "")
    gmail_password = os.getenv("GMAIL_APP_PASSWORD", "")

    if not gmail_user or not gmail_password:
        logger.warning(
            "WARNING: Gmail credentials not configured — email delivery disabled. "
            "Set GMAIL_USER and GMAIL_APP_PASSWORD in .env to enable email reports."
        )
        return False

    if not to_email:
        to_email = os.getenv("DEFAULT_RECIPIENT_EMAIL", "")

    if not to_email:
        logger.info("No recipient email address — skipping direct email.")
        return False

    subject = f"AgentX Research Report: {topic[:60]}"

    # Convert Markdown headings to HTML for the email body
    report_html = (
        report
        .replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        .replace("\n", "<br>")
    )

    html_body = f"""
<html>
<body style="font-family:Arial,sans-serif;max-width:800px;margin:0 auto;
             background:#f5f5f5;padding:20px;">

  <!-- Header -->
  <div style="background:#1a1a2e;padding:30px;border-radius:12px;
              color:#e0e0f0;margin-bottom:20px;">
    <h1 style="color:#a78bfa;margin:0 0 8px 0;font-size:1.4rem;">
      AgentX Research Report
    </h1>
    <h2 style="color:#e0e0f0;margin:0;font-size:1.1rem;">{topic}</h2>
  </div>

  <!-- Stats row -->
  <div style="background:white;padding:20px;border-radius:12px;
              margin-bottom:20px;display:flex;gap:20px;">
    <div style="flex:1;text-align:center;padding:15px;
                background:#f0f0ff;border-radius:8px;">
      <div style="font-size:1.5rem;font-weight:700;color:#6c63ff;">{word_count:,}</div>
      <div style="color:#666;font-size:0.85rem;">Words</div>
    </div>
    <div style="flex:1;text-align:center;padding:15px;
                background:#f0fff0;border-radius:8px;">
      <div style="font-size:1.5rem;font-weight:700;color:#10b981;">{avg_confidence:.0%}</div>
      <div style="color:#666;font-size:0.85rem;">Confidence</div>
    </div>
    <div style="flex:1;text-align:center;padding:15px;
                background:#fffaf0;border-radius:8px;">
      <div style="font-size:1.5rem;font-weight:700;color:#f59e0b;">${cost_usd:.6f}</div>
      <div style="color:#666;font-size:0.85rem;">Cost (USD)</div>
    </div>
  </div>

  <!-- Report body -->
  <div style="background:white;padding:30px;border-radius:12px;
              line-height:1.7;color:#333;">
    {report_html}
  </div>

  <!-- Footer -->
  <div style="text-align:center;padding:20px;color:#999;font-size:0.8rem;">
    Generated by AgentX &nbsp;·&nbsp; Task ID: {task_id[:8]}
  </div>
</body>
</html>
"""

    text_body = f"AgentX Research Report: {topic}\n\n{report}"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = gmail_user
    msg["To"] = to_email
    msg.attach(MIMEText(text_body, "plain", "utf-8"))
    msg.attach(MIMEText(html_body, "html", "utf-8"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465, timeout=15) as server:
            server.login(gmail_user, gmail_password)
            server.sendmail(gmail_user, to_email, msg.as_string())
        logger.info("Email sent to %s for task %s", to_email, task_id)
        return True
    except smtplib.SMTPAuthenticationError:
        logger.error(
            "Gmail authentication failed — check GMAIL_USER and GMAIL_APP_PASSWORD"
        )
        return False
    except Exception as exc:
        logger.error("Email delivery failed: %s", exc)
        return False
